methodes_num3.pdf: methodes_num3.tex
	pdflatex $<
	rm -f methodes_num3.aux
	rm -f methodes_num3.fdb_latexmk
	rm -f methodes_num3.fls
	rm -f methodes_num3.log

view: methodes_num3.pdf
	open methodes_num3.pdf

